spring:
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
---
spring.profiles:
  - kubernetes
server:
  port: 8080
eureka.client.enabled: false
spring:
  zipkin:
    baseUrl: http://zipkin:9411
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:kafka:9092}
  cloud:
    stream.kafka.binder.replicationFactor: 1
