server:
    port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework]": INFO
    "[org.apache.kafka.clients.consumer]": WARN
    "[root]": INFO
    
spring:
  application:
    name: audit
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
  cloud:
    function:
      definition: auditSender
    stream:
      bindings:
        auditSender-out-0:
          destination: auditMessage
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[physical_naming_strategy]": "com.luanvv.microservices.audit.config.UpperPhysicalNamingStrategy"
        "[order_inserts]": true
        "[order_updates]": true
        "[format_sql]": true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:33060/AUDIT?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bookRoot
---
spring.profiles:
  - kubernetes
server:
  port: 8080
spring.datasource.url: jdbc:mysql://mysql:3306/AUDIT?useSSL=false&serverTimezone=UTC
