server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "health"
    liquibase:
      enabled: true

logging:
  level:
    "[physical_naming_strategy]": "com.luanvv.microservices.audit.config.UpperPhysicalNamingStrategy"
    "[org.springframework]": INFO
    "[root]": INFO

spring:
  application:
    name: book-store
  main:
    lazy-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[generate_statistics]": false
        "[order_inserts]": true
        "[order_updates]": true
        "[format_sql]": true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
  datasource:
    url: jdbc:mysql://localhost:33060/BOOKSTORE?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bookRoot
