logging:
  level:
    "[org.springframework]": debug
    "[root]": INFO
    "[com.luanvv.microservices]": DEBUG
spring:
  application:
    name: book-store
  devtools:
    livereload:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    database-change-log-lock-table: BOOK_DATABASECHANGELOGLOCK
    database-change-log-table: BOOK_DATABASECHANGELOG

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
---
spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true