logging:
  level:
    "[root]": INFO

server:
  port: 9080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: bookStoreModule
        uri: lb://book-store
        predicates:
        - Path=/store/**
        filters:
        - RewritePath=/book-store/(?<segment>.*), /$\{segment}
      - id: productServiceModule
        uri: lb://product-service
        predicates:
        - Path=/store/**
        filters:
        - RewritePath=/store/(?<segment>.*), /$\{segment}
      - id: orderServiceModule
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<segment>.*), /$\{segment}
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring.profiles:
  - kubernetes
spring:
  cloud:
    gateway:
      routes:
      - id: productServiceModule
        uri: http://product-service:8080
        predicates:
        - Path=/store/**
        filters:
        - RewritePath=/store/(?<segment>.*), /$\{segment}
      - id: orderServiceModule
        uri: http://order-service:8080
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<segment>.*), /$\{segment}
