server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
rest:
  api:
    audit: ${AUDIT_URI:http://audit:8080}
management:
  endpoints:
    web:
      exposure:
        include: "*"
    liquibase:
      enabled: true

logging:
  level:
    "[org.springframework]": INFO
    "[root]": INFO

spring:
  application:
    name: product-service
  main:
    lazy-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[physical_naming_strategy]": "com.luanvv.microservices.bookstore.product.config.UpperPhysicalNamingStrategy"
        "[generate_statistics]": false
        "[order_inserts]": true
        "[order_updates]": true
        "[format_sql]": true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
  datasource:
    url: jdbc:mysql://localhost:33060/BOOKSTORE?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bookRoot
---
spring.profiles:
  - kubernetes
server:
  port: 8080
spring.datasource.url: jdbc:mysql://product-mysql:3306/BOOKSTORE?useSSL=false&serverTimezone=UTC
